version: '3.8'
services:
  app:
    build: .
    container_name: multistream-app
    restart: unless-stopped
    ports:
      - "7575:7575"
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
      - ./public/uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
      - TZ=Asia/Jakarta