version: '3.8'
services:
  app:
    build: .
    container_name: multistream-app
    restart: unless-stopped
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
      - ./public/uploads:/app/public/uploads
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=production
      - TZ=Asia/Jakarta
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    depends_on:
      - pot-provider

  pot-provider:
    image: brainicism/bgutil-ytdlp-pot-provider:latest
    container_name: multistream-pot-provider
    restart: unless-stopped
    ports:
      - "4416:4416"